export const Fetch_users="Fetch_users"
export const CREATE_USERS = 'CREATE_USERS';
export const UPDATE_USERS = 'UPDATE_USERS';
export const ACTIVATE_USERS = 'ACTIVATE_USERS';
export const DEACTIVATE_USERS = 'DEACTIVATE_USERS';
export const UPDATE_USERS_MANAGER = 'UPDATE_USERS_MANAGER';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const CREATE_USERS_SUCCESS = 'CREATE_USERS_SUCCESS';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const ACTIVATE_USERS_SUCCESS = 'ACTIVATE_USERS_SUCCESS';
export const DEACTIVATE_USERS_SUCCESS = 'DEACTIVATE_USERS_SUCCESS';
export const UPDATE_USERS_MANAGER_SUCCESS = 'UPDATE_USERS_MANAGER_SUCCESS';
export const SET_USERS_SEARCH_OPTIONS = 'SET_USERS_SEARCH_OPTIONS';
export const SET_USERS_SEARCH_OPTIONS_TYPE = 'SET_USERS_SEARCH_OPTIONS_TYPE';

